### ISSUE TITLE
Get unit test coverage of key HARK functions

### ISSUE THREAD

**Issue by econ-ark-owner** [econ-ark/OverARK#18]
We've got basic test infrastructure set up but have very low coverage of our codebase.  We want to start by making sure key HARK functions are tested, which we define as everything in:

    HARK.utilities    
    HARK.core
    HARK.interpolation
    HARK.estimation
    HARK.simulation

Our tests can be found in the [tests subdirectory](https://github.com/econ-ark/HARK/tree/master/HARK/tests).  

If you're new to HARK but experienced with unit testing, you can work on this issue by pairing with a core team member (@llorracc or @mnwhite) to develop some new tests.  Pick a method in one of the files listed above and talk with the core team members about what range of values the method should return and how it should handle invalid input, and create one or more unit tests to capture that behavior.

**Comment by llorracc** [comment]
_Chris, I moved this comment to #29 since you're not talking about unit tests here. -- Shauna_

**Comment by shaunagm** [comment]
Current coverage [posted here](https://github.com/econ-ark/OverARK/wiki/Code-coverage).
