### ISSUE TITLE
Review OTS Technical Assessment

### ISSUE THREAD

**Issue by shaunagm** [econ-ark/OverARK#21]
OTS has written a technical assessment of econ-ARK and also provided a breakdown of the assessments into a priorities list.  I've moved this information into [a google doc](https://docs.google.com/document/d/1xf6FUpv9DkcwNRIIYrJbWDjqAFTNh7yv6A0rFOrJzd8/edit#) where it's easier for us to collaboratively ask questions, via the comments tool.  Here's the plan:

- [x] @llorracc, @mnwhite, and anyone else who is interested (@albop? @pkofod? @jackiekazil?) should read through carefully and leave any questions as comments, ideally within the next 1-2 weeks
- [x] once everyone's done this, I will give OTS the heads up that we've got questions ready for them
- [ ] OTS will answer said questions, and they or I (SGM) will incorporate those answers into a final version of the technical assessment, as needed, for future reference
- [ ] SGM will post the final assessment & priorities list somewhere, probably the wiki, and will delete the google doc so as to avoid redundant information

If you would like access to the google doc and I haven't given it to you already, please ping me here.

**Comment by shaunagm** [comment]
Here's the three questions we have for OTS:

1.  Regarding the advice to use \_\_main__ methods, Matt remarked, “To the extent that the _main_ block of our files are demonstrations of models, I'm not a fan of main() functions. I'd like the agent instances created in those demos to be accessible in the main workspace after the module/main() is called.  My preferred solution to this is to move all of the model demos into dedicated demo files and have (essentially) nothing happen when model modules are called.”  Does this seem like a good approach to you?

1. Can you provide us with an example or two from our codebase of where you think NamedTuples would be appropriate?  

1. In the priorities list, you write “We haven't yet set up whatever Anaconda.org wants us to set up (a group? a product? I don't know the right jargon) so it isn't just mgerring's personal account that holds the conda-installable artifacts.”  We’re happy to do this ourselves, but can you point us in the right direction - is there a tutorial or guide to doing this that you’d recommend?  If it’s not an easy process, as a stopgap measure, we should probably switch the conda-installable artifacts from mgerring’s personal account to an econ-ark personal account.

@llorracc @mnwhite do those look good to you?  Looking for a thumbs up (or last minute corrections/additions) before sending them to OTS.

**Comment by mnwhite** [comment]
That's good.  I still need to go through and add other comments, but this
is good for now.

**Comment by shaunagm** [comment]
Just to clarify - the comments you want to add are for our future selves, not for OTS, correct?

**Comment by mnwhite** [comment]
Maybe for OTS.  Let me go through right now with a quick scan.

**Comment by mnwhite** [comment]
Okay, I just added a bunch of comments.  None of them are pressing
questions for OTS, more just statements of agreement or explanation of some
items.

**Comment by shaunagm** [comment]
I don't think OTS is going to get back to us with answers to our questions, but I think that's okay - the questions we did have weren't very pressing.  I'm closing this issue.
