### ISSUE TITLE
Set up Sphinx auto-updating

### ISSUE THREAD

**Issue by shaunagm** [econ-ark/OverARK#3]
Right now, our documentation lives in econ-ark/hark in the gh-pages branch, where it's compiled in econ-ark.github.io/hark.  We'd like to set up documentation in a separate repo if possible, or if not possible, in  econ-ark/hark/documentation (in the master branch).

Steps:

- [ ] Check that the auto-update webhook will work with submodules.  If not, the new home for docs will be in econ-ark/hark/documentation instead of their own repo.  ([This link](http://fmarco76.github.io/git%20and%20related%20services/readthedocs) may - or may not! - help.)
- [ ] If we are creating a new repository, do so and do sphinx quick-start ([instructions](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start)).  Otherwise, move existing infrastructure from gh-pages to master, into the hark/documentation branch.  The content that's already in hark/docs can go in a folder marked "old" or similar.
- [ ] Import into ReadTheDocs through account ([instructions](https://docs.readthedocs.io/en/stable/intro/import-guide.html)) (note: this should automatically set up the [webhook](https://docs.readthedocs.io/en/stable/webhooks.html) to keep it auto updated)

Other questions:
- Can we integrate docs with remarks/demarks?

**Comment by rsaavy** [comment]
I'm not the best! But I may spend my Friday's during the day... trying to figure how to set this up.

**Comment by shaunagm** [comment]
Closing this as done, as part of Erik's work moving us to ReadtheDocs.
