### ISSUE TITLE
Always update conda as well as pip install

### ISSUE THREAD

**Issue by llorracc** [econ-ark/OverARK#38]
Just spent a couple of hours running down why something wasn't working in some contexts, and finally figured out that it was because I'd installed using conda rather than pip.  If we are going to allow installations both ways, we need to be sure to keep the two methods in sync.  

At the moment, that means we need to update the conda version.

**Comment by MridulS** [comment]
conda is supposed to be in sync with pip, but as v0.10.3 breaks with python 3.8 it failed the build on conda. I have patched a fix for it, https://github.com/conda-forge/econ-ark-feedstock/pull/4. Conda should install v0.10.3 now.
