### ISSUE TITLE
Google Season of Docs 2023 - Port Econ-ARK documentation to PyData Sphinx Theme and fix up our docs building pipelines

### ISSUE THREAD

**Issue by MridulS** [econ-ark/OverARK#42]
### Problem

Econ-ARK's current documentation pipeline uses the default readthedocs theme and we use readthedocs to build and host our docs. We plan on moving to [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) to align ourselves with the broader scientific python ecosystem. The docs itself will require some plumbing work as we have some custom setup (read hacks) to generate our documentation. As part of this project we also expect the contributor to help us review the latest tools available in the python documentation ecosystem (things like nbsphinx, etc.)

Our documentation broadly covers 3 parts
- API docs
- Contributor guide
- Jupyter Notebooks for examples

All the content is already present, this project requires the contributor to work on the build and pipeline systems for our documentation generation. The technical writer would also have the flexibility to improve our docs (especially the contributor guide) if they think it requires more work.

### How would we measure success?

- A smoother build process for our documentation, and update our theme to use PyData Sphinx Theme
- Add a guide for contributors to build docs locally
- Move to github pages for building and generating our docs
- Use circle ci to build and generate docs in active PRs so contributors can look how the doc changes will affect our documentation (Stretch Goal)

### What skills would a technical writer need to work on this project?

Experience with working with sphinx, and the python documentation ecosystem.

### Volunteers

@MridulS, will help review all PRs and lead the project

### Contact info

Technical writers interested in working on this project should send an email to @MridulS. Please include links to your technical writing work or portfolio/résumé/CV.

### Budget

| Budget item   |      Amount      |  Notes |  
|----------|:-------------:|------:|
| Technical Writer - Audit our docs pipeline, move to PyData sphinx theme |  USD 12,000 | - |
| TOTAL | USD 12,000 | |

**Comment by jaskiratsingh2000** [comment]
Thank you very much @MridulS for sharing this information. I have expressed my interest and wrote an email to you and looking forward to hearing from you in this regards. Thanks!

**Comment by jaskiratsingh2000** [comment]
@MridulS Can you please look into my email once and let me know via it please? Thanks in advance!

**Comment by mehak151** [comment]
Hello @MridulS 

I'm interested in this project and have submitted my statement of interest via email. Looking forward to hearing back from you.

Have a great day!

Thanks,
Mehak

**Comment by Chinwendu20** [comment]
Hello, my understanding of this project is that it is more development work than actual writing. Is my assessment correct?

**Comment by MridulS** [comment]
Yes, it will be more towards sphinx customization, plus editing of current docs.

**Comment by Chinwendu20** [comment]
Thanks a lot for your response. I checked the season of docs website and I am confused about the deadline for hiring technical writers. I would like to know the deadline this organization would stop receiving applications.

Let me explain further
![image](https://user-images.githubusercontent.com/59079323/228882730-02ade607-d44e-4568-82a3-0ed15c39840f.png)
There is deadline here but I am confused because it says right from March 31 technical writers have already begun working with orgs

Also as no email was explicitly written in the issue description but rather a redirect to @MridulS 's github profile, are we to use send proposals to the email we see on his github profile ?

**Comment by MridulS** [comment]
Assuming we get into Google Season of Docs, we will have until 10th May to hire someone.

We will stop receiving application as soon as we have found someone :) I will update this issue and we can start working as soon as we have hired someone. Yes, please use the email id present on my profile to send in your application.

**Comment by AA-Turner** [comment]
Hi @MridulS,

I sent a brief email to your listed ``github@`` address a few minutes ago, cross referencing my account here.

Thanks,
Adam

**Comment by MridulS** [comment]
Unfortunately we weren't selected this year, thanks again for your interest everyone!
You can look at other projects participating this year at https://developers.google.com/season-of-docs/docs/participants
